#!/bin/bash
# ═══════════════════════════════════════════════════════════
# ZWISERFIT Agent Log Auto-Sync v1.0
# 用途: 每日自动将Agent运行日志commit到 agents repo
# Cron: 0 */6 * * * (每6小时)
# 原则: commit时间线不可伪造 — 凌晨3点的commit证明24×7运行
# ═══════════════════════════════════════════════════════════

set -e

REPO_DIR="/home/agentuser/.openclaw/workspace"
AGENTS_LOG_DIR="${REPO_DIR}/data/ZWISERFIT/github-staging/agents/logs"
GIT_REMOTE="origin"
LOG_TAG="[AgentLogSync]"

log() { echo "$(date '+%Y-%m-%dT%H:%M:%S%z') ${LOG_TAG} $1"; }

# 收集各Agent今日运行摘要
TODAY=$(date '+%Y-%m-%d')
LOG_FILE="${AGENTS_LOG_DIR}/${TODAY}.md"

# 生成每日运行日志
cat > "$LOG_FILE" << EOF
# Agent Run Log — ${TODAY}

> Auto-generated by ZWISERFIT Agent Log Sync.
> Commit timestamp proves 24×7 autonomous operation.

## Active Agents Today

EOF

# 检查每个Agent的最近session活动
declare -A AGENTS
AGENTS=(
    ["Shuyu"]="agent:main"
    ["Zeus"]="agent:zeus"
    ["Nova"]="agent:nova"
    ["Tristan"]="agent:tech_lead"
    ["Stella"]="agent:security_lead"
    ["Ethan"]="agent:effect_lead"
    ["Baron"]="agent:brand_lead"
    ["Luna"]="agent:luna"
    ["Momo"]="momo_bridge"
)

for agent in "${!AGENTS[@]}"; do
    session_key="${AGENTS[$agent]}"
    # 检查是否有今日活动
    LAST_ACTIVE=$(find /home/agentuser/.openclaw/agents/*/sessions/ -name "*.jsonl" -newer "${AGENTS_LOG_DIR}/.last_sync" 2>/dev/null | head -1)
    if [ -n "$LAST_ACTIVE" ]; then
        echo "- **${agent}** 🟢 Active" >> "$LOG_FILE"
    else
        echo "- **${agent}** ⚪ No activity this cycle" >> "$LOG_FILE"
    fi
done

cat >> "$LOG_FILE" << EOF

## Infrastructure Health

- **SOS Sync:** $(systemctl is-active sos-sync.timer 2>/dev/null || echo "unknown")
- **Syncthing:** $(systemctl is-active syncthing@agentuser 2>/dev/null || echo "unknown")
- **Gateway:** $(systemctl is-active openclaw-gateway 2>/dev/null || echo "unknown")

## Cross-Validation Events

$(grep -c "CRITICAL" /home/agentuser/.openclaw/workspace/tech_lead/data/ZWISERFIT/AIreports/Tristan/syncthing-watchdog.log 2>/dev/null || echo "0") watchdog alerts today.

---

*Generated: $(date '+%Y-%m-%dT%H:%M:%S%z') | Commit: auto*
EOF

# Git commit & push
cd "$REPO_DIR"
git add "data/ZWISERFIT/github-staging/agents/logs/${TODAY}.md" 2>/dev/null
git commit -m "[AgentLogSync] ${TODAY} — 9-Agent daily run log" 2>/dev/null || log "No changes to commit"
git push "$GIT_REMOTE" main 2>/dev/null || log "⚠️ Push failed — will retry next cycle"

# Update sync marker
touch "${AGENTS_LOG_DIR}/.last_sync"
log "✅ Sync complete — $(wc -l < "$LOG_FILE") lines"
